export type BookMotif =
  | "lattice"
  | "corrosion"
  | "efficiency"
  | "network"
  | "boom"
  | "organization"
  | "schematic"
  | "flight"
  | "circuit"
  | "orbit"
  | "branches"
  | "wave"
  | "runner"
  | "gather"
  | "maze"
  | "fracture"
  | "continuum"
  | "windows"
  | "steps";

export type CatalogBook = {
  id: string;
  title: string;
  shortTitle: string;
  author: string;
  description: string;
  quote: string;
  quoteBy: string;
  format: string;
  /** Static fallback; ProgressLibrary refreshes from /api/shelf-availability. */
  availability: string;
  url: string;
  cover: string;
  accent: string;
  ink: string;
  motif: BookMotif;
  height: number;
  thickness: number;
  /** Live copy counts, refreshed client-side. */
  totalCopies?: number;
  availableCopies?: number;
  isbn?: string;
  /** Optional local front-cover art under public/books/<id>/. */
  coverImage?: string;
  linkLabel?: string;
  living?: boolean;
};

/**
 * TRAC Library catalog — generated from trac_library.books
 * (Supabase project cphkxgykshjeultzgzmz).
 * Availability is a build-time snapshot; the shelf refreshes it live.
 * Borrow URLs resolve against NEXT_PUBLIC_LIBRARY_ORIGIN at runtime
 * (see borrowUrl helper in site-config).
 */

export const catalog: CatalogBook[] = ([
  {
    id: "21st-century-literature-from-the-philippines-and",
    title: "21st Century Literature from the Philippines and the World",
    shortTitle: "21st Century Literature from",
    author: "Department of Education",
    description: "21st Century Literature from the Philippines and the World by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-001",
    availability: "4 of 4 available",
    url: `borrowUrl("SAMPLE-DEPED-001")`,
    cover: "#602424",
    accent: "#d3b069",
    ink: "#f7f3ea",
    motif: "lattice",
    height: 1.85,
    thickness: 0.14,
    totalCopies: 4,
    availableCopies: 4,
    isbn: "SAMPLE-DEPED-001",
  },
  {
    id: "agricultural-engineering-and-farm-machinery",
    title: "Agricultural Engineering and Farm Machinery",
    shortTitle: "Agricultural Engineering and",
    author: "Department of Agriculture",
    description: "Agricultural Engineering and Farm Machinery by Department of Agriculture, published 2015. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015 \u00b7 ISBN SAMPLE-ENG-001",
    availability: "2 of 2 available",
    url: `borrowUrl("SAMPLE-ENG-001")`,
    cover: "#603024",
    accent: "#d3c569",
    ink: "#f7f3ea",
    motif: "network",
    height: 2.22,
    thickness: 0.15,
    totalCopies: 2,
    availableCopies: 2,
    isbn: "SAMPLE-ENG-001",
  },
  {
    id: "animal-science-livestock-and-poultry",
    title: "Animal Science: Livestock and Poultry",
    shortTitle: "Animal Science: Livestock and",
    author: "Department of Agriculture",
    description: "Animal Science: Livestock and Poultry by Department of Agriculture, published 2015. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015 \u00b7 ISBN SAMPLE-AGR-002",
    availability: "2 of 2 available",
    url: `borrowUrl("SAMPLE-AGR-002")`,
    cover: "#603c24",
    accent: "#ccd369",
    ink: "#f7f3ea",
    motif: "orbit",
    height: 2.09,
    thickness: 0.16,
    totalCopies: 2,
    availableCopies: 2,
    isbn: "SAMPLE-AGR-002",
  },
  {
    id: "aquaculture-and-fisheries-management",
    title: "Aquaculture and Fisheries Management",
    shortTitle: "Aquaculture and Fisheries",
    author: "Department of Agriculture",
    description: "Aquaculture and Fisheries Management by Department of Agriculture, published 2015. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015 \u00b7 ISBN SAMPLE-AGR-003",
    availability: "2 of 2 available",
    url: `borrowUrl("SAMPLE-AGR-003")`,
    cover: "#604824",
    accent: "#b7d369",
    ink: "#f7f3ea",
    motif: "branches",
    height: 1.96,
    thickness: 0.17,
    totalCopies: 2,
    availableCopies: 2,
    isbn: "SAMPLE-AGR-003",
  },
  {
    id: "art-appreciation",
    title: "Art Appreciation",
    shortTitle: "Art Appreciation",
    author: "Commission on Higher Education",
    description: "Art Appreciation by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-005",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-005")`,
    cover: "#605424",
    accent: "#a2d369",
    ink: "#f7f3ea",
    motif: "wave",
    height: 2.33,
    thickness: 0.18,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-005",
  },
  {
    id: "contemporary-philippine-arts-from-the-regions",
    title: "Contemporary Philippine Arts from the Regions",
    shortTitle: "Contemporary Philippine Arts",
    author: "Department of Education",
    description: "Contemporary Philippine Arts from the Regions by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-007",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-DEPED-007")`,
    cover: "#606024",
    accent: "#8cd369",
    ink: "#f7f3ea",
    motif: "maze",
    height: 2.2,
    thickness: 0.19,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-DEPED-007",
  },
  {
    id: "crop-science-and-production",
    title: "Crop Science and Production",
    shortTitle: "Crop Science and Production",
    author: "Department of Agriculture",
    description: "Crop Science and Production by Department of Agriculture, published 2015. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015 \u00b7 ISBN SAMPLE-AGR-001",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-AGR-001")`,
    cover: "#546024",
    accent: "#77d369",
    ink: "#f7f3ea",
    motif: "steps",
    height: 2.07,
    thickness: 0.2,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-AGR-001",
  },
  {
    id: "earth-and-life-science",
    title: "Earth and Life Science",
    shortTitle: "Earth and Life Science",
    author: "Department of Education",
    description: "Earth and Life Science by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-003",
    availability: "4 of 4 available",
    url: `borrowUrl("SAMPLE-DEPED-003")`,
    cover: "#486024",
    accent: "#69d370",
    ink: "#f7f3ea",
    motif: "windows",
    height: 1.94,
    thickness: 0.21,
    totalCopies: 4,
    availableCopies: 4,
    isbn: "SAMPLE-DEPED-003",
  },
  {
    id: "el-filibusterismo",
    title: "El Filibusterismo",
    shortTitle: "El Filibusterismo",
    author: "Jos\u00e9 Rizal",
    description: "El Filibusterismo by Jos\u00e9 Rizal, published 1891. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 1891 \u00b7 ISBN SAMPLE-LIT-002",
    availability: "2 of 2 available",
    url: `borrowUrl("SAMPLE-LIT-002")`,
    cover: "#3c6024",
    accent: "#69d385",
    ink: "#f7f3ea",
    motif: "circuit",
    height: 2.31,
    thickness: 0.22,
    totalCopies: 2,
    availableCopies: 2,
    isbn: "SAMPLE-LIT-002",
  },
  {
    id: "entrepreneurship",
    title: "Entrepreneurship",
    shortTitle: "Entrepreneurship",
    author: "Department of Education",
    description: "Entrepreneurship by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-006",
    availability: "4 of 4 available",
    url: `borrowUrl("SAMPLE-DEPED-006")`,
    cover: "#306024",
    accent: "#69d39b",
    ink: "#f7f3ea",
    motif: "continuum",
    height: 2.18,
    thickness: 0.23,
    totalCopies: 4,
    availableCopies: 4,
    isbn: "SAMPLE-DEPED-006",
  },
  {
    id: "environmental-science",
    title: "Environmental Science",
    shortTitle: "Environmental Science",
    author: "Department of Education",
    description: "Environmental Science by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-008",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-DEPED-008")`,
    cover: "#246024",
    accent: "#69d3b0",
    ink: "#f7f3ea",
    motif: "efficiency",
    height: 2.05,
    thickness: 0.24,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-DEPED-008",
  },
  {
    id: "ethics",
    title: "Ethics",
    shortTitle: "Ethics",
    author: "Commission on Higher Education",
    description: "Ethics by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-006",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-006")`,
    cover: "#246030",
    accent: "#69d3c5",
    ink: "#f7f3ea",
    motif: "schematic",
    height: 1.92,
    thickness: 0.25,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-006",
  },
  {
    id: "florante-at-laura",
    title: "Florante at Laura",
    shortTitle: "Florante at Laura",
    author: "Francisco Balagtas",
    description: "Florante at Laura by Francisco Balagtas, published 1838. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 1838 \u00b7 ISBN SAMPLE-LIT-003",
    availability: "2 of 2 available",
    url: `borrowUrl("SAMPLE-LIT-003")`,
    cover: "#24603c",
    accent: "#69ccd3",
    ink: "#f7f3ea",
    motif: "flight",
    height: 2.29,
    thickness: 0.26,
    totalCopies: 2,
    availableCopies: 2,
    isbn: "SAMPLE-LIT-003",
  },
  {
    id: "fundamentals-of-physics",
    title: "Fundamentals of Physics",
    shortTitle: "Fundamentals of Physics",
    author: "Department of Education",
    description: "Fundamentals of Physics by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-011",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-DEPED-011")`,
    cover: "#246048",
    accent: "#69b7d3",
    ink: "#f7f3ea",
    motif: "gather",
    height: 2.16,
    thickness: 0.27,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-DEPED-011",
  },
  {
    id: "general-biology",
    title: "General Biology",
    shortTitle: "General Biology",
    author: "Department of Education",
    description: "General Biology by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-009",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-DEPED-009")`,
    cover: "#246054",
    accent: "#69a2d3",
    ink: "#f7f3ea",
    motif: "runner",
    height: 2.03,
    thickness: 0.28,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-DEPED-009",
  },
  {
    id: "general-chemistry",
    title: "General Chemistry",
    shortTitle: "General Chemistry",
    author: "Department of Education",
    description: "General Chemistry by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-010",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-DEPED-010")`,
    cover: "#246060",
    accent: "#698cd3",
    ink: "#f7f3ea",
    motif: "corrosion",
    height: 1.9,
    thickness: 0.29,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-DEPED-010",
  },
  {
    id: "general-mathematics",
    title: "General Mathematics",
    shortTitle: "General Mathematics",
    author: "Department of Education",
    description: "General Mathematics by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-002",
    availability: "4 of 4 available",
    url: `borrowUrl("SAMPLE-DEPED-002")`,
    cover: "#245460",
    accent: "#6977d3",
    ink: "#f7f3ea",
    motif: "organization",
    height: 2.27,
    thickness: 0.3,
    totalCopies: 4,
    availableCopies: 4,
    isbn: "SAMPLE-DEPED-002",
  },
  {
    id: "introduction-to-information-technology",
    title: "Introduction to Information Technology",
    shortTitle: "Introduction to Information",
    author: "Commission on Higher Education",
    description: "Introduction to Information Technology by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-010",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-010")`,
    cover: "#244860",
    accent: "#7069d3",
    ink: "#f7f3ea",
    motif: "fracture",
    height: 2.14,
    thickness: 0.31,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-010",
  },
  {
    id: "mathematics-in-the-modern-world",
    title: "Mathematics in the Modern World",
    shortTitle: "Mathematics in the Modern",
    author: "Commission on Higher Education",
    description: "Mathematics in the Modern World by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-003",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-003")`,
    cover: "#243c60",
    accent: "#8569d3",
    ink: "#f7f3ea",
    motif: "boom",
    height: 2.01,
    thickness: 0.32,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-003",
  },
  {
    id: "noli-me-tangere",
    title: "Noli Me Tangere",
    shortTitle: "Noli Me Tangere",
    author: "Jos\u00e9 Rizal",
    description: "Noli Me Tangere by Jos\u00e9 Rizal, published 1887. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 1887 \u00b7 ISBN SAMPLE-LIT-001",
    availability: "2 of 2 available",
    url: `borrowUrl("SAMPLE-LIT-001")`,
    cover: "#243060",
    accent: "#9b69d3",
    ink: "#f7f3ea",
    motif: "lattice",
    height: 1.88,
    thickness: 0.33,
    totalCopies: 2,
    availableCopies: 2,
    isbn: "SAMPLE-LIT-001",
  },
  {
    id: "personal-development",
    title: "Personal Development",
    shortTitle: "Personal Development",
    author: "Department of Education",
    description: "Personal Development by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-005",
    availability: "4 of 4 available",
    url: `borrowUrl("SAMPLE-DEPED-005")`,
    cover: "#242460",
    accent: "#b069d3",
    ink: "#f7f3ea",
    motif: "network",
    height: 2.25,
    thickness: 0.34,
    totalCopies: 4,
    availableCopies: 4,
    isbn: "SAMPLE-DEPED-005",
  },
  {
    id: "purposive-communication",
    title: "Purposive Communication",
    shortTitle: "Purposive Communication",
    author: "Commission on Higher Education",
    description: "Purposive Communication by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-002",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-002")`,
    cover: "#302460",
    accent: "#c569d3",
    ink: "#f7f3ea",
    motif: "orbit",
    height: 2.12,
    thickness: 0.35,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-002",
  },
  {
    id: "readings-in-philippine-history",
    title: "Readings in Philippine History",
    shortTitle: "Readings in Philippine History",
    author: "Commission on Higher Education",
    description: "Readings in Philippine History by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-004",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-004")`,
    cover: "#3c2460",
    accent: "#d369cc",
    ink: "#f7f3ea",
    motif: "branches",
    height: 1.99,
    thickness: 0.14,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-004",
  },
  {
    id: "rizal-life-and-works",
    title: "Rizal: Life and Works",
    shortTitle: "Rizal: Life and Works",
    author: "Commission on Higher Education",
    description: "Rizal: Life and Works by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-009",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-009")`,
    cover: "#482460",
    accent: "#d369b7",
    ink: "#f7f3ea",
    motif: "wave",
    height: 1.86,
    thickness: 0.15,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-009",
  },
  {
    id: "science-technology-and-society",
    title: "Science, Technology and Society",
    shortTitle: "Science, Technology and",
    author: "Commission on Higher Education",
    description: "Science, Technology and Society by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-007",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-007")`,
    cover: "#542460",
    accent: "#d369a2",
    ink: "#f7f3ea",
    motif: "maze",
    height: 2.23,
    thickness: 0.16,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-007",
  },
  {
    id: "soil-science-and-conservation",
    title: "Soil Science and Conservation",
    shortTitle: "Soil Science and Conservation",
    author: "Department of Agriculture",
    description: "Soil Science and Conservation by Department of Agriculture, published 2015. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015 \u00b7 ISBN SAMPLE-AGR-004",
    availability: "2 of 2 available",
    url: `borrowUrl("SAMPLE-AGR-004")`,
    cover: "#602460",
    accent: "#d3698c",
    ink: "#f7f3ea",
    motif: "steps",
    height: 2.1,
    thickness: 0.17,
    totalCopies: 2,
    availableCopies: 2,
    isbn: "SAMPLE-AGR-004",
  },
  {
    id: "the-contemporary-world",
    title: "The Contemporary World",
    shortTitle: "The Contemporary World",
    author: "Commission on Higher Education",
    description: "The Contemporary World by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-008",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-008")`,
    cover: "#602454",
    accent: "#d36977",
    ink: "#f7f3ea",
    motif: "windows",
    height: 1.97,
    thickness: 0.18,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-008",
  },
  {
    id: "understanding-culture-society-and-politics",
    title: "Understanding Culture, Society and Politics",
    shortTitle: "Understanding Culture,",
    author: "Department of Education",
    description: "Understanding Culture, Society and Politics by Department of Education, published 2016. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016 \u00b7 ISBN SAMPLE-DEPED-004",
    availability: "4 of 4 available",
    url: `borrowUrl("SAMPLE-DEPED-004")`,
    cover: "#602448",
    accent: "#d37069",
    ink: "#f7f3ea",
    motif: "circuit",
    height: 2.34,
    thickness: 0.19,
    totalCopies: 4,
    availableCopies: 4,
    isbn: "SAMPLE-DEPED-004",
  },
  {
    id: "understanding-the-self",
    title: "Understanding the Self",
    shortTitle: "Understanding the Self",
    author: "Commission on Higher Education",
    description: "Understanding the Self by Commission on Higher Education, published 2018. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018 \u00b7 ISBN SAMPLE-CHED-001",
    availability: "3 of 3 available",
    url: `borrowUrl("SAMPLE-CHED-001")`,
    cover: "#60243c",
    accent: "#d38569",
    ink: "#f7f3ea",
    motif: "continuum",
    height: 2.21,
    thickness: 0.2,
    totalCopies: 3,
    availableCopies: 3,
    isbn: "SAMPLE-CHED-001",
  },
  {
    id: "up-diksiyonaryong-filipino",
    title: "UP Diksiyonaryong Filipino",
    shortTitle: "UP Diksiyonaryong Filipino",
    author: "Virgilio S. Almario",
    description: "UP Diksiyonaryong Filipino by Virgilio S. Almario, published 2010. Held in the TRAC Library collection under General.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2010 \u00b7 ISBN SAMPLE-REF-001",
    availability: "2 of 2 available",
    url: `borrowUrl("SAMPLE-REF-001")`,
    cover: "#602430",
    accent: "#d39b69",
    ink: "#f7f3ea",
    motif: "efficiency",
    height: 2.08,
    thickness: 0.21,
    totalCopies: 2,
    availableCopies: 2,
    isbn: "SAMPLE-REF-001",
  },
]);
