export type BookMotif =
  | "lattice"
  | "corrosion"
  | "efficiency"
  | "network"
  | "boom"
  | "organization"
  | "schematic"
  | "flight"
  | "circuit"
  | "orbit"
  | "branches"
  | "wave"
  | "runner"
  | "gather"
  | "maze"
  | "fracture"
  | "continuum"
  | "windows"
  | "steps";

export type CatalogBook = {
  id: string;
  title: string;
  shortTitle: string;
  author: string;
  description: string;
  quote: string;
  quoteBy: string;
  format: string;
  availability: string;
  url: string;
  cover: string;
  accent: string;
  ink: string;
  motif: BookMotif;
  height: number;
  thickness: number;
  /** Optional local front-cover art under public/books/<id>/. */
  coverImage?: string;
  linkLabel?: string;
  living?: boolean;
};


export const catalog: CatalogBook[] = ([
  {
    id: "21st-century-literature-from-the-philipp",
    title: "21st Century Literature from the Philippines and the World",
    shortTitle: "21st Century Literature from the Philipp",
    author: "Department of Education",
    description: "21st Century Literature from the Philippines and the World \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-001.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "4 of 4 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-001",
    cover: "#6f2130",
    accent: "#d5a756",
    ink: "#f4ead7",
    motif: "lattice",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "agricultural-engineering-and-farm-machin",
    title: "Agricultural Engineering and Farm Machinery",
    shortTitle: "Agricultural Engineering and Farm Machin",
    author: "Department of Agriculture",
    description: "Agricultural Engineering and Farm Machinery \u2014 Department of Agriculture, 2015. ISBN SAMPLE-ENG-001.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015",
    availability: "2 of 2 available",
    url: "/borrow?isbn=" + "SAMPLE-ENG-001",
    cover: "#1f3a5f",
    accent: "#8fb8de",
    ink: "#eef4fa",
    motif: "network",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "animal-science-livestock-and-poultry",
    title: "Animal Science: Livestock and Poultry",
    shortTitle: "Animal Science: Livestock and Poultry",
    author: "Department of Agriculture",
    description: "Animal Science: Livestock and Poultry \u2014 Department of Agriculture, 2015. ISBN SAMPLE-AGR-002.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015",
    availability: "2 of 2 available",
    url: "/borrow?isbn=" + "SAMPLE-AGR-002",
    cover: "#2f4a2f",
    accent: "#c9b26b",
    ink: "#f2efe2",
    motif: "orbit",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "aquaculture-and-fisheries-management",
    title: "Aquaculture and Fisheries Management",
    shortTitle: "Aquaculture and Fisheries Management",
    author: "Department of Agriculture",
    description: "Aquaculture and Fisheries Management \u2014 Department of Agriculture, 2015. ISBN SAMPLE-AGR-003.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015",
    availability: "2 of 2 available",
    url: "/borrow?isbn=" + "SAMPLE-AGR-003",
    cover: "#5b2d86",
    accent: "#cdb6ec",
    ink: "#f6f0fb",
    motif: "branches",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "art-appreciation",
    title: "Art Appreciation",
    shortTitle: "Art Appreciation",
    author: "Commission on Higher Education",
    description: "Art Appreciation \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-005.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-005",
    cover: "#7a3b12",
    accent: "#e8b98a",
    ink: "#fdf3ea",
    motif: "wave",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "contemporary-philippine-arts-from-the-re",
    title: "Contemporary Philippine Arts from the Regions",
    shortTitle: "Contemporary Philippine Arts from the Re",
    author: "Department of Education",
    description: "Contemporary Philippine Arts from the Regions \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-007.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-007",
    cover: "#12494f",
    accent: "#9ed3cf",
    ink: "#eefaf8",
    motif: "maze",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "crop-science-and-production",
    title: "Crop Science and Production",
    shortTitle: "Crop Science and Production",
    author: "Department of Agriculture",
    description: "Crop Science and Production \u2014 Department of Agriculture, 2015. ISBN SAMPLE-AGR-001.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-AGR-001",
    cover: "#6f2130",
    accent: "#d5a756",
    ink: "#f4ead7",
    motif: "steps",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "earth-and-life-science",
    title: "Earth and Life Science",
    shortTitle: "Earth and Life Science",
    author: "Department of Education",
    description: "Earth and Life Science \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-003.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "4 of 4 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-003",
    cover: "#1f3a5f",
    accent: "#8fb8de",
    ink: "#eef4fa",
    motif: "windows",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "el-filibusterismo",
    title: "El Filibusterismo",
    shortTitle: "El Filibusterismo",
    author: "Jos\u00e9 Rizal",
    description: "El Filibusterismo \u2014 Jos\u00e9 Rizal, 1891. ISBN SAMPLE-LIT-002.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 1891",
    availability: "2 of 2 available",
    url: "/borrow?isbn=" + "SAMPLE-LIT-002",
    cover: "#2f4a2f",
    accent: "#c9b26b",
    ink: "#f2efe2",
    motif: "circuit",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "entrepreneurship",
    title: "Entrepreneurship",
    shortTitle: "Entrepreneurship",
    author: "Department of Education",
    description: "Entrepreneurship \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-006.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "4 of 4 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-006",
    cover: "#5b2d86",
    accent: "#cdb6ec",
    ink: "#f6f0fb",
    motif: "continuum",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "environmental-science",
    title: "Environmental Science",
    shortTitle: "Environmental Science",
    author: "Department of Education",
    description: "Environmental Science \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-008.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-008",
    cover: "#7a3b12",
    accent: "#e8b98a",
    ink: "#fdf3ea",
    motif: "lattice",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "ethics",
    title: "Ethics",
    shortTitle: "Ethics",
    author: "Commission on Higher Education",
    description: "Ethics \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-006.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-006",
    cover: "#12494f",
    accent: "#9ed3cf",
    ink: "#eefaf8",
    motif: "network",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "florante-at-laura",
    title: "Florante at Laura",
    shortTitle: "Florante at Laura",
    author: "Francisco Balagtas",
    description: "Florante at Laura \u2014 Francisco Balagtas, 1838. ISBN SAMPLE-LIT-003.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 1838",
    availability: "2 of 2 available",
    url: "/borrow?isbn=" + "SAMPLE-LIT-003",
    cover: "#6f2130",
    accent: "#d5a756",
    ink: "#f4ead7",
    motif: "orbit",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "fundamentals-of-physics",
    title: "Fundamentals of Physics",
    shortTitle: "Fundamentals of Physics",
    author: "Department of Education",
    description: "Fundamentals of Physics \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-011.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-011",
    cover: "#1f3a5f",
    accent: "#8fb8de",
    ink: "#eef4fa",
    motif: "branches",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "general-biology",
    title: "General Biology",
    shortTitle: "General Biology",
    author: "Department of Education",
    description: "General Biology \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-009.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-009",
    cover: "#2f4a2f",
    accent: "#c9b26b",
    ink: "#f2efe2",
    motif: "wave",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "general-chemistry",
    title: "General Chemistry",
    shortTitle: "General Chemistry",
    author: "Department of Education",
    description: "General Chemistry \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-010.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-010",
    cover: "#5b2d86",
    accent: "#cdb6ec",
    ink: "#f6f0fb",
    motif: "maze",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "general-mathematics",
    title: "General Mathematics",
    shortTitle: "General Mathematics",
    author: "Department of Education",
    description: "General Mathematics \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-002.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "4 of 4 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-002",
    cover: "#7a3b12",
    accent: "#e8b98a",
    ink: "#fdf3ea",
    motif: "steps",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "introduction-to-information-technology",
    title: "Introduction to Information Technology",
    shortTitle: "Introduction to Information Technology",
    author: "Commission on Higher Education",
    description: "Introduction to Information Technology \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-010.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-010",
    cover: "#12494f",
    accent: "#9ed3cf",
    ink: "#eefaf8",
    motif: "windows",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "mathematics-in-the-modern-world",
    title: "Mathematics in the Modern World",
    shortTitle: "Mathematics in the Modern World",
    author: "Commission on Higher Education",
    description: "Mathematics in the Modern World \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-003.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-003",
    cover: "#6f2130",
    accent: "#d5a756",
    ink: "#f4ead7",
    motif: "circuit",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "noli-me-tangere",
    title: "Noli Me Tangere",
    shortTitle: "Noli Me Tangere",
    author: "Jos\u00e9 Rizal",
    description: "Noli Me Tangere \u2014 Jos\u00e9 Rizal, 1887. ISBN SAMPLE-LIT-001.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 1887",
    availability: "2 of 2 available",
    url: "/borrow?isbn=" + "SAMPLE-LIT-001",
    cover: "#1f3a5f",
    accent: "#8fb8de",
    ink: "#eef4fa",
    motif: "continuum",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "personal-development",
    title: "Personal Development",
    shortTitle: "Personal Development",
    author: "Department of Education",
    description: "Personal Development \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-005.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "4 of 4 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-005",
    cover: "#2f4a2f",
    accent: "#c9b26b",
    ink: "#f2efe2",
    motif: "lattice",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "purposive-communication",
    title: "Purposive Communication",
    shortTitle: "Purposive Communication",
    author: "Commission on Higher Education",
    description: "Purposive Communication \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-002.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-002",
    cover: "#5b2d86",
    accent: "#cdb6ec",
    ink: "#f6f0fb",
    motif: "network",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "readings-in-philippine-history",
    title: "Readings in Philippine History",
    shortTitle: "Readings in Philippine History",
    author: "Commission on Higher Education",
    description: "Readings in Philippine History \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-004.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-004",
    cover: "#7a3b12",
    accent: "#e8b98a",
    ink: "#fdf3ea",
    motif: "orbit",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "rizal-life-and-works",
    title: "Rizal: Life and Works",
    shortTitle: "Rizal: Life and Works",
    author: "Commission on Higher Education",
    description: "Rizal: Life and Works \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-009.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-009",
    cover: "#12494f",
    accent: "#9ed3cf",
    ink: "#eefaf8",
    motif: "branches",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "science-technology-and-society",
    title: "Science, Technology and Society",
    shortTitle: "Science, Technology and Society",
    author: "Commission on Higher Education",
    description: "Science, Technology and Society \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-007.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-007",
    cover: "#6f2130",
    accent: "#d5a756",
    ink: "#f4ead7",
    motif: "wave",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "soil-science-and-conservation",
    title: "Soil Science and Conservation",
    shortTitle: "Soil Science and Conservation",
    author: "Department of Agriculture",
    description: "Soil Science and Conservation \u2014 Department of Agriculture, 2015. ISBN SAMPLE-AGR-004.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2015",
    availability: "2 of 2 available",
    url: "/borrow?isbn=" + "SAMPLE-AGR-004",
    cover: "#1f3a5f",
    accent: "#8fb8de",
    ink: "#eef4fa",
    motif: "maze",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "the-contemporary-world",
    title: "The Contemporary World",
    shortTitle: "The Contemporary World",
    author: "Commission on Higher Education",
    description: "The Contemporary World \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-008.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-008",
    cover: "#2f4a2f",
    accent: "#c9b26b",
    ink: "#f2efe2",
    motif: "steps",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "understanding-culture-society-and-politi",
    title: "Understanding Culture, Society and Politics",
    shortTitle: "Understanding Culture, Society and Polit",
    author: "Department of Education",
    description: "Understanding Culture, Society and Politics \u2014 Department of Education, 2016. ISBN SAMPLE-DEPED-004.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2016",
    availability: "4 of 4 available",
    url: "/borrow?isbn=" + "SAMPLE-DEPED-004",
    cover: "#5b2d86",
    accent: "#cdb6ec",
    ink: "#f6f0fb",
    motif: "windows",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "understanding-the-self",
    title: "Understanding the Self",
    shortTitle: "Understanding the Self",
    author: "Commission on Higher Education",
    description: "Understanding the Self \u2014 Commission on Higher Education, 2018. ISBN SAMPLE-CHED-001.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2018",
    availability: "3 of 3 available",
    url: "/borrow?isbn=" + "SAMPLE-CHED-001",
    cover: "#7a3b12",
    accent: "#e8b98a",
    ink: "#fdf3ea",
    motif: "circuit",
    height: 2.05,
    thickness: 0.22,
  },
  {
    id: "up-diksiyonaryong-filipino",
    title: "UP Diksiyonaryong Filipino",
    shortTitle: "UP Diksiyonaryong Filipino",
    author: "Virgilio S. Almario",
    description: "UP Diksiyonaryong Filipino \u2014 Virgilio S. Almario, 2010. ISBN SAMPLE-REF-001.",
    quote: "",
    quoteBy: "",
    format: "Print \u00b7 2010",
    availability: "2 of 2 available",
    url: "/borrow?isbn=" + "SAMPLE-REF-001",
    cover: "#12494f",
    accent: "#9ed3cf",
    ink: "#eefaf8",
    motif: "continuum",
    height: 2.05,
    thickness: 0.22,
  },
]);
